### ISSUE TITLE
Help getting this running on a Raspberry Pi?

### ISSUE THREAD

**Issue by CaptClaude** [generalelectrix/pyenttec#2]
Are you able/willing/in a position to help me get this running on a Raspberry Pi?
I need some nudges in the right direction to get moving.  I can clone this repo to the Pi and as you might imagine, dmx.select_port() does not work.  As a Python Noob with 40+ years of engineering experience but only a few Python projects behind me, I'm a bit stumped. I haven't found any examples of this running under Linux that provide any guidance -- if you have one, that would be great.  If I get it working, I can flesh out the documentation for future users -- if you're interested.
Thanks.

**Comment by willstott101** [comment]
Hi, I'm using this under Ubuntu currently in Python 3. So there may be minor differences when using Python 2.

Hopefully this isn't too late.

Instead of using select_port at all (this is ) I would instantiate a `DMXConnection` directly and explicitly pass in the path of a serial port. I've found this by listing the contents of `/dev/serial/by-id/`.

i.e.
`conn = DMXConnection('/dev/serial/by-id/usb-ENTTEC_DMX_USB_PRO_blah_blah')`

Good luck.

For what it's worth it's reasonably trivial to add support for other platforms in `select_port` and I have a branch which does this for Linux. I was hoping to get my first PR https://github.com/generalelectrix/pyenttec/pull/1 in before I go for that one though.

**Comment by generalelectrix** [comment]
@willstott101 thanks for chiming in!  I don't have a hardware linux box to test on.

**Comment by CaptClaude** [comment]
After Googling around for a while, I eventually found out how to do what I needed to do. I ended up modifying the DmxPy library and porting it to Python 3 to accomplish my very simple task. I probably broke some rules, but it works.  Thanks @willstott101 for your input.

**Comment by dstelzer** [comment]
@CaptClaude If you have code that works for a RasPi, have you posted it anywhere? I'm dealing with that same problem now.

**Comment by CaptClaude** [comment]
@dstelzer -- If I were a real Github user and software geek, I'd have done all sorts of things like forking the code and so on.  But I'm not (sad face).  I'd be more than happy to send it to you.

**Comment by dstelzer** [comment]
@CaptClaude It would be appreciated. I can see about getting it back on Github afterward if you like. Attach the zip file here?
