### ISSUE TITLE
Question about baud rate in __init__.py

### ISSUE THREAD

**Issue by HJ959** [generalelectrix/pyenttec#5]
Hello, been playing with this a while and was just wondering why the baud rate is 57600 in __init__.py? 

From looking online the DMX baud rate is 250kbp/s? Is it to do with the enttec device?

Cheers! This repo is super useful!

**Comment by willstott101** [comment]
That's the serial connection over USB to the Enttec not the baud rate of the actual dmx output. IDK why that value is what it is, or if it's important though.

**Comment by HJ959** [comment]
Okay no worries thanks!

**Comment by generalelectrix** [comment]
I believe that value isn’t actually used by the port since it is a virtual com port, but it is a safe dummy value that will pass possible validation by an underlying serial library.

**Comment by generalelectrix** [comment]
Indeed, from the [API spec](https://dol2kh495zr52.cloudfront.net/pdf/misc/dmx_usb_pro_api_spec.pdf):
"Since the driver is a virtual COM port, the baudrate setting used to open this COM port is a dummy value, and does not control the USB communication speed."
The value of that constant was probably arbitrary to begin with and likely ported directly from the Objective-C implementation that I used as the basis for this library.
